config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/" => "home#index", as: :root
  get "/AboutUs" => "home#aboutuspage", as: :aboutus
  delete "/signout" => "home#destroy", as: :destroy_session

  get "/signin" => "users#signinpage", as: :new_sessions
  post "/signin" => "users#signin", as: :sessions
  get "/signup" => "users#signuppage", as: :new_user
  post "/signup" => "users#signup", as: :users

  resources :admin_users
  resources :admin_menu
  resources :admin_menu_category
  get "/report" => "admin_users#report", as: :admin_report

  get "/menu" => "orders#index", as: :menu
  get "/history" => "orders#history", as: :history
  put "/delivered/:id" => "orders#delivered", as: :delivered
  resources :orders
  resources :order_items
end

app/views/admin/menu.html.erb
<div class="shopping-cart sidebar-collapse">
  <div class="page-header header-filter shopping-background" data-parallax="true" filter-color="blue" style="height:120px">
  </div>
  <div class="main main-raised">
    <div class="card card-plain">
      <div class="card-body">
        <div class="row justify-content-center">
          <div class="col-md-10">
            <br>
            <h1 class="card-title text-center">Menu</h1>

            <% opt = []
               MenuCategory.all.each do |cat|
                 opt << [cat.name, cat.id]
               end %>

            <% MenuCategory.all.each do |category| %>
              <div class="table-responsive">
                <div class="row">

                  <tr class="text-center">
                    <div class="col-md-9">
                      <%= form_with(url: "/admin_menu_category/#{category.id}", method: "put") do |form| %>
                        <%= label_tag(:status, "Status") %> &nbsp;
                        <%= check_box_tag(:status, !category.status, category.status, class: "btn btn-link togglebutton", :onclick => "this.form.submit()") %>
                      <% end %>
                      <%= form_with(url: "/admin_menu_category/#{category.id}", method: "put") do |form| %>
                        <%= form.text_field :name, class: "form-control", value: category.name.upcase %>
                    </div>

                    <td class="td-actions">
                      <div class="btn-group">

                        <button onclick="this.form.submit()" class="btn btn-success btn-link">
                          <i class="material-icons">save</i>
                        </button>
                      <% end %>

                        <button onclick="<%= "categoryOpen#{category.id}()" %> " class="btn btn-primary btn-link">
                          <i class="material-icons">add</i>
                        </button>

                        <%= form_with(url: "/admin_menu_category/#{category.id}", method: "delete") do %>
                          <button onclick="this.form.submit()" class="btn btn-danger btn-link">
                            <i class="material-icons">delete</i>
                          </button>
                        <% end %>

                      </div>
                    </td>
                  </tr>
                </div>

                <table class="table table-shopping">
                  <thead>
                    <tr class="text-center">
                      <th>#</th>
                      <th>Name</th>
                      <th>Description</th>
                      <th>Price</th>
                      <th>Category</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>

                    <% index = 1 %>
                    <% MenuItem.where(menu_category_id: category.id).each do |menu| %>
                      <tr class="text-center">

                        <%= form_with(url: "/admin_menu/#{menu.id}", method: "put") do |form| %>
                          <td><%= index %></td>
                          <% index += 1 %>
                          <td>
                            <%= form.text_field :name, class: "form-control", value: menu.name %>
                          </td>
                          <td>
                            <%= form.text_field :description, class: "form-control", value: menu.description %>
                          </td>
                          <td>
                            <%= form.text_field :price, class: "form-control", value: menu.price %>
                          </td>
                          <td>
                            <%= select_tag(:menu_category_id, options_for_select(
                                  opt, category.id
                                ), class: "btn btn-link") %>
                          </td>
                          <td class="td-actions">
                            <div class="btn-group">

                              <button onclick="this.form.submit()" class="btn btn-success btn-link btn-just-icon btn-sm">
                                <i class="material-icons">save</i>
                              </button>
                        <% end %>

                          <%= form_with(url: "/admin_menu/#{menu.id}", method: "delete") do %>
                            <button onclick="this.form.submit()" class="btn btn-danger btn-link">
                              <i class="material-icons">delete</i>
                            </button>
                          <% end %>

                          <%= form_with(url: "/admin_menu/#{menu.id}", method: "put") do %>
                            <%= label_tag(:status, "Status") %> &nbsp;
                            <%= check_box_tag(:status, menu.status ? 0 : 1, menu.status, class: "btn btn-link togglebutton", :onclick => "this.form.submit()") %>
                          <% end %>
                          </div>
                        </td>
                      </tr>
                    <% end %>

                  </tbody>
                </table>
              </div>

              <div id=<%= category.id.to_s %> class="form col-md-6 justify-content-center">
                <%= form_with(url: admin_menu_index_path, method: "post") do |form| %>
                  <%= form.text_field :name, class: "form-control", autofocus: true, placeholder: "Enter item name" %>
                  <%= form.text_field :description, class: "form-control", placeholder: "Enter description" %>
                  <%= form.text_field :price, class: "form-control", placeholder: "Enter item price" %>
                  <%= select_tag(:menu_category_id, options_for_select(
                        opt, category.id
                      ), class: "btn btn-round btn-link") %>
                  <%= form.submit "Add Item", class: "btn btn-rose btn-round" %>
                <% end %>
                <button class="btn btn-rose btn-round btn-block" onclick="<%= "categoryClose#{category.id}()" %> ">Close</button>
              </div>

              <script>
                document.getElementById(<%= category.id.to_s %>).style.display = "none";
                function <%= "categoryOpen#{category.id}()" %> {
                  document.getElementById(<%= category.id.to_s %>).style.display = "block";
                }

                function <%= "categoryClose#{category.id}()" %> {
                  document.getElementById(<%= category.id.to_s %>).style.display = "none";
                }
              </script>
              <hr/>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<li class="btn btn-link nav-link">
  <button class="btn btn-rose btn-round btn-block" onclick="openForm()">Add new category</button>
</li>

<div id="newCategory" class="form col-md-6 justify-content-center">
  <%= form_with(url: admin_menu_category_index_path, method: "post") do |form| %>
    <%= form.text_field :name, class: "form-control", autofocus: true, placeholder: "Enter new category name..." %>
    <%= form.submit "Add Category", class: "btn btn-rose btn-round" %>
  <% end %>
  <button class="btn btn-rose btn-round btn-block" onclick="closeForm()">Close</button>
</div>

<script>
  document.getElementById("newCategory").style.display = "none";
  function openForm() {
    document.getElementById("newCategory").style.display = "block";
  }

  function closeForm() {
    document.getElementById("newCategory").style.display = "none";
  }
</script>

 <script>
  document.getElementById("name").addEventListener('keyup', function(event) {
    if(event.code === 'Enter') {
      event.prevetnDefault();
      document.querySelector('form').submit();
    }
  })
</script>

app/views/admin/report.html.erb
<div class="shopping-cart sidebar-collapse">
  <div class="page-header header-filter shopping-background" data-parallax="true" filter-color="blue" style="height:120px">
  </div>
  <div class="main main-raised">
    <div class="card card-plain">
      <div class="card-body">
        <div class="row justify-content-center">
          <div class="col-lg-10 col-md-10">

            <%= form_with(url: admin_report_path, method: "get", class: "form-container") do |form| %>
              <div class="row">
                <div class="col-md-5">
                  <h1 class="card-title text-center">All Orders</h1>
                </div>
                <div class="form-group col-md-3">
                  <%= label_tag("from_date", nil, class: "label-control") %>
                  <%= date_field_tag("from_date", @from, class: "form-control datepicker") %>
                </div>
                <div class="form-group col-md-3">
                  <%= label_tag("to_date", nil, class: "label-control") %>
                  <%= date_field_tag("to_date", @to, class: "form-control datepicker") %>
                </div>
                <div class="col-md-1">
                  <button onclick="this.form.submit()" class="btn btn-info btn-link">
                    Click here
                    <br/><i class="material-icons">filter</i><br/>
                    to filter
                  </button>
                </div>
              </div>
            <% end %>
            <br/><br/>

            <div class="row">

              <% allTotal = 0 %>
              <% temp = [@offline, @online] %>

              <% for user in temp %>

                <% cat1Total = 0 %>
                <div class="col-lg-6 col-md-6 border-left border-right">

                  <h3 class="card-title text-center">
                    <%= user.first.role == "customer" ? "Online" : "Offline" %>
                  </h3>
                  <hr/>

                  <% for x in [:pending, :delivered] %>

                    <% cat2Total = 0 %>
                    <% orders = @order.where(user_id: user.ids, status: x).order(:date) %>

                    <div class="table-responsive">
                      <h4 class="text-center card-title"><%= x.upcase %></h4>

                      <table class="table table-shopping text-center">
                        <thead>
                          <tr class="text-center">
                            <th>#</th>
                            <th>Date</th>
                            <% if user.first.role == "customer" %>
                              <th>UserName</th>
                            <% end %>
                            <th>Total Amount</th>
                            <th>Actions</th>
                          </tr>
                        </thead>

                        <tbody>
                          <% index = 1 %>
                          <% orders.each do |order| %>

                            <% total = 0 %>
                            <% order.order_items.each do |orderItem| %>
                              <% total += orderItem.menu_item_price.to_i * orderItem.menu_item_quantity.to_i %>
                            <% end %>

                            <tr class="text-center">
                              <td><%= index %></td>
                                  <% index += 1 %>
                              <td>
                                <%= order.date %>
                              </td>
                              <% if user.first.role == "customer" %>
                                <td>
                                  <%= order.user.first_name %>
                                </td>
                              <% end %>
                              <td>
                                <%= total %>
                                <% cat2Total += total %>
                              </td>
                              <td class="td-actions">
                                <%= form_with(url: "/order_items/#{order.id}", method: "get", class: "form-container") do |form| %>
                                  <button onclick="this.form.submit()" class="btn btn-success btn-link">
                                    <i class="material-icons">visibility</i>
                                  </button>
                                <% end %>
                              </td>
                            </tr>
                          <% end %>
                        </tbody>

                        <tfoot class="text-center">
                          <tr>
                            <% if user.first.role == "customer" %>
                              <td></td>
                            <% end %>
                            <td></td>
                            <td class="td-total text-center">
                              Total
                            </td>
                            <td colspan="1" class="td-price text-center">
                              <small>
                                &#8377;
                                <%= cat2Total %>
                                <% cat1Total += cat2Total %>
                              </small>
                            </td>
                            <td></td>
                          </tr>
                        </tfoot>
                      </table>
                    </div>
                    <hr/>
                  <% end %>

                  <h4 class="text-center">
                      Total
                      <%= user.first.role == "customer" ? "online" : "offline" %>
                      amount =
                      <small>
                        &#8377;
                      </small>
                      <%= cat1Total %>
                      <% allTotal += cat1Total %>
                  </h4>
                  <hr/>
                </div>
              <% end %>
            </div>
            <hr/>
            <div>
              <h3 class="text-center">
                      Overall total amount =
                      <small>
                        &#8377;
                      </small>
                      <%= allTotal %>
                  </h3>
            </div>
            <hr/>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users.html.erb
<div class="shopping-cart sidebar-collapse">
  <div class="page-header header-filter shopping-background" data-parallax="true" filter-color="blue" style="height:120px">
  </div>
  <div class="main main-raised">
    <div class="card card-plain">
      <div class="card-body">
        <div class="row justify-content-center">
          <div class="col-lg-10 col-md-10">
            <br>
            <h1 class="card-title text-center">Users</h1>

            <% arr = ["owner", "clerk", "customer"] %>
            <% for x in arr %>
              <% users = User.where(:role => x) %>

                <div class="table-responsive">
                  <h4 class="text-center"><small><%= x.upcase %></small></h4>
                  <table class="table table-shopping">
                    <thead>
                      <tr class="text-center">
                        <th>#</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Since</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <tbody>

                      <% index = 1 %>
                      <% users.each do |user| %>
                        <tr class="text-center">
                          <%= form_with(url: "/admin_users/#{user.id}", method: "put", class: "form-container") do |form| %>
                            <td><%= index %></td>
                                <% index += 1 %>
                            <td>
                              <%= form.text_field :first_name, class: "form-control", placeholder: "First Name...", value: user.first_name %>
                            </td>
                            <td>
                              <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name...", value: user.last_name %>
                            </td>
                            <td>
                              <%= form.email_field :email, class: "form-control", placeholder: "Email...", value: user.email %>
                            </td>
                            <td>
                              <% cat = ["owner", "clerk", "customer"]
                                 int_cat = cat.find_index(user.role) %>
                              <%= select_tag(:role, options_for_select([["owner", 0], ["clerk", 1], ["customer", 2]], int_cat), class: "btn btn-link") %>
                            </td>
                            <td><%= user.created_at.to_s(:short) %></td>
                            <td class="td-actions">
                              <button onclick="this.form.submit()" class="btn btn-success btn-link">
                                <i class="material-icons">save</i>
                              </button>
                            </td>
                          <% end %>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <hr/>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<li class="btn btn-link nav-link">
  <button class="btn btn-rose btn-round btn-block" onclick="openForm1()">Add new user</button>
</li>

<div id="newUser" class="form col-md-6 justify-content-center">
  <%= form_with(url: admin_users_path, method: "post") do |form| %>
    <%= form.text_field :first_name, class: "form-control", autofocus: true, placeholder: "First Name..." %>
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name..." %>
    <%= form.email_field :email, class: "form-control", placeholder: "Email..." %>
    <%= form.password_field :password, class: "form-control", placeholder: "Password..." %>
    <%= select_tag(:role, options_for_select([["owner", 0], ["clerk", 1]], 0), class: "btn btn-link") %>
    <%= form.submit "Add User", class: "btn btn-rose btn-round" %>
  <% end %>
  <button class="btn btn-rose btn-round btn-block" onclick="closeForm1()">Close</button>
</div>

<script>
  document.getElementById("newUser").style.display = "none";
  function openForm1() {
    document.getElementById("newUser").style.display = "block";
  }

  function closeForm1() {
    document.getElementById("newUser").style.display = "none";
  }
</script>