config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/" => "home#index", as: :root
  get "/AboutUs" => "home#aboutuspage", as: :aboutus
  delete "/signout" => "home#destroy", as: :destroy_session

  get "/signin" => "users#signinpage", as: :new_sessions
  post "/signin" => "users#signin", as: :sessions
  get "/signup" => "users#signuppage", as: :new_user
  post "/signup" => "users#signup", as: :users

  resources :admin_users
  resources :admin_menu
  resources :admin_menu_category
  get "/report" => "admin_users#report", as: :admin_report

  get "/menu" => "orders#index", as: :menu
  get "/history" => "orders#history", as: :history
  put "/delivered/:id" => "orders#delivered", as: :delivered
  resources :orders
  resources :order_items
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:owner, :clerk, :customer]
  has_many :orders

  validates :first_name, presence: true
  validates :email, presence: true

  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :sign_page

  def signinpage
    render "signin"
  end

  def signuppage
    render "signup"
  end

  def signup
    user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
      role: 2,
    )
    if user.save
      session[:current_user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  def signin
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Your login attempt was invalid. Please retry."
      redirect_to new_sessions_path
    end
  end
end

app/views/users/new.html.erb
<div class="signup-page sidebar-collapse">
<div class="page-header header-filter login-background">
    <div class="container">
      <div class="row">
        <div class="col-md-10 ml-auto mr-auto">
          <div class="card card-signup">
            <h2 class="card-title text-center">Register</h2>
            <div class="card-body">
              <div class="row">
                <div class="col-md-5 ml-auto">
                  <div class="info info-horizontal">
                    <div class="icon icon-rose">
                      <i class="material-icons">timeline</i>
                    </div>
                    <div class="description">
                      <h4 class="info-title">Your vehicle, your time</h4>
                      <p class="description">
                        Grab your car, bike, scooter, or even shoes and deliver whenever you want—for an hour, a weekend, or throughout the week.
                      </p>
                    </div>
                  </div>
                  <div class="info info-horizontal">
                    <div class="icon icon-primary">
                      <i class="material-icons">payments</i>
                    </div>
                    <div class="description">
                      <h4 class="info-title">Weekly payments</h4>
                      <p class="description">
                        Get paid once a week and easily keep track of money you've made within the driver app.
                      </p>
                    </div>
                  </div>
                  <div class="info info-horizontal">
                    <div class="icon icon-info">
                      <i class="material-icons">group</i>
                    </div>
                    <div class="description">
                      <h4 class="info-title">Enjoy your city</h4>
                      <p class="description">
                        Between picking up and dropping off deliveries, it’s just you and the road—relax, bump your music, and enjoy cruising around town.
                      </p>
                    </div>
                  </div>
                </div>
                <div class="col-md-5 mr-auto">
                  <div class="social text-center">
                    <button class="btn btn-just-icon btn-round btn-twitter">
                      <i class="fa fa-twitter"></i>
                    </button>
                    <button class="btn btn-just-icon btn-round btn-google">
                      <i class="fa fa-google"></i>
                    </button>
                    <button class="btn btn-just-icon btn-round btn-facebook">
                      <i class="fa fa-facebook"> </i>
                    </button>
                    <h4> or be classical </h4>
                  </div>
                  <div class="form">
                    <%= form_with url: users_path do |form| %>
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text">
                            <i class="material-icons">face</i>
                          </span>
                        </div>
                        <%= form.text_field :first_name, class: "form-control", autofocus: true, placeholder: "First Name..." %>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text">
                            <i class="material-icons">face</i>
                          </span>
                        </div>
                        <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name..." %>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text">
                            <i class="material-icons">mail</i>
                          </span>
                        </div>
                        <%= form.email_field :email, class: "form-control", placeholder: "Email..." %>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text">
                            <i class="material-icons">lock_outline</i>
                          </span>
                        </div>
                        <%= form.password_field :password, class: "form-control", placeholder: "Password..." %>
                      </div>
                    </div>
                    <div class="form-check">
                      <label class="form-check-label">
                        <%= form.check_box :checkbox, checked: true, class: "form-check-input" %>
                        <span class="form-check-sign">
                          <span class="check"></span>
                        </span>
                        I agree to the <a href="#something">terms and conditions</a>.
                      </label>
                    </div>
                    <div class="text-center">
                      <%= form.submit "Get Started", class: "btn btn-primary btn-round" %>
                    </div>
                    <% end %>
                  </div>
                <br/>
                <div class="text-center">Already have an account?
                    <%= link_to :"Sign in here!", new_sessions_path%>
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/users/signin.html.erb
<div class="login-page sidebar-collapse">
  <div class="page-header header-filter login-background">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-8 ml-auto mr-auto">
          <div class="form">
            <%= form_with url: sessions_path do |form| %>
              <div class="card card-login card-hidden">
                <div class="card-header card-header-primary text-center">
                  <h4 class="card-title">Login</h4>
                  <div class="social-line">
                    <a href="#futureWork" class="btn btn-just-icon btn-link btn-white">
                      <i class="fa fa-facebook-square"></i>
                    </a>
                    <a href="#futureWork" class="btn btn-just-icon btn-link btn-white">
                      <i class="fa fa-twitter"></i>
                    </a>
                    <a href="#futureWork" class="btn btn-just-icon btn-link btn-white">
                      <i class="fa fa-google-plus"></i>
                    </a>
                  </div>
                </div>
                <div class="card-body ">
                  <p class="card-description text-center">Or Be Classical</p>
                  <span class="bmd-form-group">
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="material-icons">email</i>
                        </span>
                      </div>
                      <%= form.email_field :email, class: "form-control", autofocus: true, placeholder: "Email..." %>
                    </div>
                  </span>

                  <span class="bmd-form-group">
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <i class="material-icons">lock_outline</i>
                        </span>
                      </div>
                      <%= form.password_field :password, class: "form-control", placeholder: "Password..." %>
                    </div>
                  </span>

                  <div class="card-footer justify-content-center">
                    <%= form.submit "Lets Go", class: "btn btn-rose btn-round" %>
                  </div>

                  <div class="card-footer justify-content-center">New User?
                    <%= link_to :"Sign up here!", new_user_path %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/signup.html.erb
<div class="signup-page sidebar-collapse">
<div class="page-header header-filter login-background">
    <div class="container">
      <div class="row">
        <div class="col-md-10 ml-auto mr-auto">
          <div class="card card-signup">
            <h2 class="card-title text-center">Register</h2>
            <div class="card-body">
              <div class="row">
                <div class="col-md-5 ml-auto">
                  <div class="info info-horizontal">
                    <div class="icon icon-rose">
                      <i class="material-icons">timeline</i>
                    </div>
                    <div class="description">
                      <h4 class="info-title">Heading1</h4>
                      <p class="description">
                        Any thoughts, will fill it later.
                      </p>
                    </div>
                  </div>
                  <div class="info info-horizontal">
                    <div class="icon icon-primary">
                      <i class="material-icons">payments</i>
                    </div>
                    <div class="description">
                      <h4 class="info-title">Heading2</h4>
                      <p class="description">
                        Any thoughts, will fill it later.
                      </p>
                    </div>
                  </div>
                  <div class="info info-horizontal">
                    <div class="icon icon-info">
                      <i class="material-icons">group</i>
                    </div>
                    <div class="description">
                      <h4 class="info-title">Heading3</h4>
                      <p class="description">
                        Any thoughts, will fill it later.
                      </p>
                    </div>
                  </div>
                </div>
                <div class="col-md-5 mr-auto">
                  <div class="social text-center">
                    <button class="btn btn-just-icon btn-round btn-twitter">
                      <i class="fa fa-twitter"></i>
                    </button>
                    <button class="btn btn-just-icon btn-round btn-google">
                      <i class="fa fa-google"></i>
                    </button>
                    <button class="btn btn-just-icon btn-round btn-facebook">
                      <i class="fa fa-facebook"> </i>
                    </button>
                    <h4> or be classical </h4>
                  </div>
                  <div class="form">
                    <%= form_with url: users_path do |form| %>
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text">
                            <i class="material-icons">face</i>
                          </span>
                        </div>
                        <%= form.text_field :first_name, class: "form-control", autofocus: true, placeholder: "First Name..." %>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text">
                            <i class="material-icons">face</i>
                          </span>
                        </div>
                        <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name..." %>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text">
                            <i class="material-icons">mail</i>
                          </span>
                        </div>
                        <%= form.email_field :email, class: "form-control", placeholder: "Email..." %>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text">
                            <i class="material-icons">lock_outline</i>
                          </span>
                        </div>
                        <%= form.password_field :password, class: "form-control", placeholder: "Password..." %>
                      </div>
                    </div>
                    <div class="form-check">
                      <label class="form-check-label">
                        <%= form.check_box :checkbox, checked: true, class: "form-check-input" %>
                        <span class="form-check-sign">
                          <span class="check"></span>
                        </span>
                        I agree to the <a href="#something">terms and conditions</a>.
                      </label>
                    </div>
                    <div class="text-center">
                      <%= form.submit "Get Started", class: "btn btn-primary btn-round" %>
                    </div>
                    <% end %>
                  </div>
                <br/>
                <div class="text-center">Already have an account?
                    <%= link_to :"Sign in here!", new_sessions_path %>
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>