config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/" => "home#index", as: :root
  get "/AboutUs" => "home#aboutuspage", as: :aboutus
  delete "/signout" => "home#destroy", as: :destroy_session

  get "/signin" => "users#signinpage", as: :new_sessions
  post "/signin" => "users#signin", as: :sessions
  get "/signup" => "users#signuppage", as: :new_user
  post "/signup" => "users#signup", as: :users

  resources :admin_users
  resources :admin_menu
  resources :admin_menu_category
  get "/report" => "admin_users#report", as: :admin_report

  get "/menu" => "orders#index", as: :menu
  get "/history" => "orders#history", as: :history
  put "/delivered/:id" => "orders#delivered", as: :delivered
  resources :orders
  resources :order_items
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :current_user

  def index
    render "index"
  end

  def aboutuspage
    render "aboutus"
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end
end

app/views/home/aboutus.html.erb
<div class="about-us sidebar-collapse">
  <div class="page-header header-small about-background" style="opacity: 0.8" data-parallax="true">
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto text-center" style="opacity: 1">
          <h1 class="title">About Us</h1>
          <h4>Meet the amazing team behind this project and find out more about how we work.</h4>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="about-description text-center">
        <div class="row">
          <div class="col-md-8 ml-auto mr-auto">
            <h5 class="description">Cafeteria is an online food ordering platform. Users can read menus and order food from the cafeteria using an application on the iOS or Android platforms, or through a web browser.</h5>
          </div>
        </div>
      </div>
      <div class="about-team team-1">
        <div class="row">
          <div class="col-md-8 ml-auto mr-auto text-center">
            <h2 class="title">We are nerd rockstars</h2>
            <h5 class="description">I build this project as the final Milestone target for the WEB201 course provided by Pupilfirst.school</h5>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div class="card card-profile card-plain">
              <div class="card-avatar">
                <a href="#pablo">
                  <img class="img teammate1">
                </a>
              </div>
              <div class="card-body">
                <h4 class="card-title">Future Team-mate 1</h4>
                <h6 class="category text-muted">#Skills</h6>
                <p class="card-description">
                  Anything to say
                </p>
              </div>
              <div class="card-footer justify-content-center">
                <a href="#pablo" class="btn btn-just-icon btn-link btn-twitter">
                  <i class="fa fa-twitter"></i>
                </a>
                <a href="#pablo" class="btn btn-just-icon btn-link btn-github">
                  <i class="fa fa-github"></i>
                </a>
                <a href="#pablo" class="btn btn-just-icon btn-link btn-linkedin">
                  <i class="fa fa-linkedin"></i>
                </a>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card card-profile card-plain">
              <div class="card-avatar">
                <a href="#pablo">
                  <img class="img profile-img">
                </a>
              </div>
              <div class="card-body">
                <h4 class="card-title">Shubhank Singhal</h4>
                <h6 class="category text-muted">Web Developer</h6>
                <p class="card-description">
                  Well, Rome wasn't built in a day so this project.
                </p>
              </div>
              <div class="card-footer justify-content-center">
                <a href="https://github.com/ShubhankSinghal" class="btn btn-just-icon btn-link btn-github"><i class="fa fa-github"></i></a>
                <a href="https://www.facebook.com/shubhank41/" class="btn btn-just-icon btn-link btn-facebook"><i class="fa fa-facebook-square"></i></a>
                <a href="https://www.instagram.com/shubhank_singhal/" class="btn btn-just-icon btn-link btn-instagram"><i class="fa fa-instagram"></i></a>
                <a href="https://www.linkedin.com/in/shubhanksinghal/" class="btn btn-just-icon btn-link btn-linkedin"><i class="fa fa-linkedin"></i></a>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card card-profile card-plain">
              <div class="card-avatar">
                <a href="#pablo">
                  <img class="img teammate2">
                </a>
              </div>
              <div class="card-body">
                <h4 class="card-title">Future Team-mate 2</h4>
                <h6 class="category text-muted">#Skills</h6>
                <p class="card-description">
                  Anything to say.
                </p>
              </div>
              <div class="card-footer justify-content-center">
                <a href="#pablo" class="btn btn-just-icon btn-link btn-twitter">
                  <i class="fa fa-twitter"></i>
                </a>
                <a href="#pablo" class="btn btn-just-icon btn-link btn-github">
                  <i class="fa fa-github"></i>
                </a>
                <a href="#pablo" class="btn btn-just-icon btn-link btn-linkedin">
                  <i class="fa fa-linkedin"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="landing-page sidebar-collapse">
  <div class="page-header <%= @current_user ? "header-filter home1-background" : "home-background" %>"  filter-color="green" data-parallax="true">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-left">

          <% if !@current_user %>

            <h1 class="title">Hungry? You're in the right place</h1>
            <div class="col-md-2 text-left"><%= link_to :"Sign in here!", new_sessions_path, class: "btn btn-rose btn-round btn-block" %></div>
            <br>

          <% else %>

            <h1 class="title">Welcome <%= @current_user.first_name %>!</h1>
            <br>

            <% if @current_user.role == "owner" %>

              <%= link_to "Manage Users", admin_users_path, class: "btn btn-danger btn-raised btn-round btn-lg" %>
              <br/> <br/>
              <%= link_to "Manage Menu", admin_menu_index_path, class: "btn btn-danger btn-raised btn-round btn-lg" %>
              <br/> <br/>
              <%= link_to "View all orders", admin_report_path, class: "btn btn-danger btn-raised btn-round btn-lg" %>
              <br/> <br/>

            <% end %>

            <% if @current_user.role == "customer" %>
              <h4>Well, what are you waiting for?</h4>
              <h4>Click on the button below and get your food ordered...</h4>
              <br/>
            <% end %>

            <%= link_to @current_user.role != "customer" ? "Place an Order" : "Order now", menu_path, class: "btn btn-danger btn-raised btn-round btn-lg" %>
            <br/> <br/>
            <%= link_to @current_user.role != "customer" ? "Update orders' status" : "Check your orders", history_path, class: "btn btn-danger btn-raised btn-round btn-lg" %>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>