config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/" => "home#index", as: :root
  get "/AboutUs" => "home#aboutuspage", as: :aboutus
  delete "/signout" => "home#destroy", as: :destroy_session

  get "/signin" => "users#signinpage", as: :new_sessions
  post "/signin" => "users#signin", as: :sessions
  get "/signup" => "users#signuppage", as: :new_user
  post "/signup" => "users#signup", as: :users

  resources :admin_users
  resources :admin_menu
  resources :admin_menu_category
  get "/report" => "admin_users#report", as: :admin_report

  get "/menu" => "orders#index", as: :menu
  get "/history" => "orders#history", as: :history
  put "/delivered/:id" => "orders#delivered", as: :delivered
  resources :orders
  resources :order_items
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeteriaManagement</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_pack_tag "logo.png" %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body class="index-page">
    <div class="header-3">
      <nav class="navbar navbar-transparent navbar-absolute navbar-expand-lg">
        <div class="container">

          <div class="navbar-translate">
            <a class="navbar-brand" href="/">
              <span style="font-size: 32px;" class="title">
                <span style="color:#F00;">Cafe</span>
                <span style="color:#0F0;">teria</span>
              </span>
            </a>

            <button class="ml-auto navbar-toggler" type="button" data-toggle="collapse" aria-controls="topNav" aria-expanded="false" aria-label="Toggle navigation" data-target="#topNav">
              <span class="sr-only">Toggle navigation</span>
              <span class="navbar-toggler-icon"></span>
              <span class="navbar-toggler-icon"></span>
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>

          <div class="collapse navbar-collapse" id="topNav">
            <ul class="navbar-nav ml-auto">

              <li class="nav-link">
                <%= link_to "About Us", aboutus_path, method: "get", class: "btn  btn-rose btn-round btn-block" %>
              </li>

              <% if @current_user %>

                <% if request.original_fullpath == menu_path %>
                  <li class="button-container nav-link iframe-extern">
                    <%= link_to "Checkout", order_items_path, method: "get", class: "btn  btn-rose btn-round btn-block" %>
                  </li>
                <% end %>

                <li class="button-container nav-link iframe-extern">
                  <%= link_to "Sign-out", destroy_session_path, method: "delete", class: "btn  btn-rose btn-round btn-block" %>
                </li>

              <% elsif request.original_fullpath == new_user_path %>

                <li class="button-container nav-link iframe-extern">
                    <%= link_to "Login", new_sessions_path, method: "get", class: "btn  btn-rose btn-round btn-block" %>
                </li>

              <% else %>

                <li class="button-container nav-link iframe-extern">
                  <%= link_to "Register", users_path, method: "get", class: "btn  btn-rose btn-round btn-block" %>
                </li>

              <% end %>
            </ul>
          </div>
        </div>
      </nav>

      <% if flash[:error] %>
        <div class="alert alert-danger fixed-bottom">
          <div class="container">
            <div class="alert-icon">
              <i class="material-icons">error_outline</i>
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true"><i class="material-icons">clear</i></span>
            </button>
            <b>Error Alert: </b> <%= flash[:error] %>
          </div>
        </div>
        <div class="clearfix"></div>
      <% end %>

      <%= yield %>

      <footer class="footer footer-black footer-big">
        <div class="container">
          <div class="content">
            <div class="row">
              <div class="col-md-3">
                <a href="/" class="copyright pull-center">
                  <span style="font-size: 32px;" class="title">
                    <span style="color:#F00;">Cafe</span>
                    <span style="color:#0F0;">teria</span>
                  </span>
                </a>
              </div>
              <div class="col-md-3">
                <h5>About Cafeteria</h5>
                <ul class="links-vertical">
                  <li>
                     <%= link_to "Read our Blog", "#futureWork" %>
                  </li>
                  <li>
                    <%= link_to "Buy Gifts Cards", "#futureWork" %>
                  </li>
                  <li>
                    <%= link_to "Create a business account", "#futureWork" %>
                  </li>
                  <li>
                    <%= link_to "Add your Restaurant", "#futureWork" %>
                  </li>
                  <li>
                    <%= link_to "Sign up to deliver", "#futureWork" %>
                  </li>
                </ul>
              </div>
              <div class="col-md-3">
                <h5>Get Help</h5>
                <ul class="links-vertical">
                  <li>
                    <%= link_to "View all cities", "#futureWork" %>
                  </li>
                  <li>
                    <%= link_to "View all countries", "#futureWork" %>
                  </li>
                  <li>
                    <%= link_to "Restaurant near me", "#futureWork" %>
                  </li>
                  <li>
                    <%= link_to "Save on your first order", "#futureWork" %>
                  </li>
                  <li>
                    <%= link_to "English", "#futureWork" %>
                  </li>
                </ul>
              </div>

              <div class="col-md-3">
                <h5>Follow Us</h5>
                <ul class="social-buttons">
                  <li>
                    <a href="#futureWork" class="btn btn-just-icon btn-link btn-twitter">
                      <i class="fa fa-twitter"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#futureWork" class="btn btn-just-icon btn-link btn-facebook">
                      <i class="fa fa-facebook-square"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#futureWork" class="btn btn-just-icon btn-link btn-instagram">
                      <i class="fa fa-instagram"></i>
                    </a>
                  </li>
                </ul>
                <ul class="links-vertical">
                  <li>
                    <%= link_to "Privacy Policies", "#futureWork" %>
                  </li>
                  <li>
                    <%= link_to "Terms", "#futureWork" %>
                  </li>
                  <li>
                    <%= link_to "Pricing", "#futureWork" %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <hr>
          <div class="copyright pull-center">
            Copyright &#xA9; Shubhank Singhal All Rights Reserved.
          </div>
        </div>
      </footer>
    </div>
  </body>
</html>